name: C/C++ clang-format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Format
        uses: DoozyX/clang-format-lint-action@v0.12
        with:
          clangFormatVersion: 12
